### ISSUE TITLE
Suggestion: provide example of how the data is parsed

### ISSUE THREAD

**Issue by iiiii7d** [MRT-Map/sheets-api#1]
For example, I have a table
A|B|C
D|E|F
G|H|I

How would this appear in JSON? I hope that this would make the API easier to use because of a visual demonstration.
Thanks :D
-- i____7d

**Comment by Dinty1** [comment]
Roger, will work on that

**Comment by Dinty1** [comment]
[Done.](https://github.com/MRT-Map/sheets-api/commit/eb227e48e1c575cf266ed56a31f7f7331afcba07)
